/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacion_series;

import javax.swing.JOptionPane;

/**
 *
 * @author PC-1
 */
public class Aplicacion extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnSeriesPares = new javax.swing.JButton();
        btnSeriePrimos = new javax.swing.JButton();
        btnSerieFibonacci = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMostrarResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Aplicación de Series");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Desarrollado por: Bryan Kender Mendoza Canaviri");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Cantidad de elementos:");

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        btnSeriesPares.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSeriesPares.setText("Series Pares");
        btnSeriesPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeriesParesActionPerformed(evt);
            }
        });

        btnSeriePrimos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSeriePrimos.setText("Serie Primos");
        btnSeriePrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeriePrimosActionPerformed(evt);
            }
        });

        btnSerieFibonacci.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSerieFibonacci.setText("Serie Fibonacci");
        btnSerieFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerieFibonacciActionPerformed(evt);
            }
        });

        txtAreaMostrarResultado.setColumns(20);
        txtAreaMostrarResultado.setRows(5);
        jScrollPane1.setViewportView(txtAreaMostrarResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSeriesPares, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSerieFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeriePrimos, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeriesPares, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSerieFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeriePrimos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnSeriesParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeriesParesActionPerformed
        try
        {
          //almacenar N el numero escrito en el cuadro de texto
        //convirtiendolo a un numero a entero
        int N = Integer.valueOf(txtCantidad.getText());
        int par=2;
        String resultado = "";
        
        for (int i=1; i<=N; i++)
        {
            resultado = resultado + par + ", ";
            par += 2;
        }
        
        //convertir el entero N a un String 
        //resultado = String.valueOf(N);
        //Mostrar resultado en el text Area
         mostrar (resultado);
        }
        catch(Exception e){
              txtAreaMostrarResultado.setText("Error, ingrese un numero entero positivo");
              JOptionPane.showMessageDialog(this, "No es el número correcto", "Atencion", HEIGHT);
        }  
    }//GEN-LAST:event_btnSeriesParesActionPerformed

    private void btnSerieFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerieFibonacciActionPerformed
        try{
            int N = Integer.valueOf(txtCantidad.getText());
            long a=0, b=1, c;
            String resultado="";
            
            for(int i=1; i <=N ; i++)
            {
                resultado = resultado + a + ",   ";
                c = a + b;
                a = b;
                b = c;
            }
            mostrar (resultado);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error, ingrese un nuemro entero positivo! ");
        }
    }//GEN-LAST:event_btnSerieFibonacciActionPerformed

    private void btnSeriePrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeriePrimosActionPerformed
        try{
            int N = Integer.valueOf(txtCantidad.getText());
            int a=2, c=1, cd, i;
            String resultado = "";
            while (c<=N)
            {
                cd = 0;
                
                for(i=2 ; i<= Math.sqrt(a); i++)
                {
                    if(a % i == 0)
                        cd++;
                }
                if(cd == 0)
                {
                  resultado = resultado + a + ",  ";
                  c++;
                }
                a++;
            }
            mostrar (resultado);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error inserte un numero entero y positivo");
        }
    }//GEN-LAST:event_btnSeriePrimosActionPerformed
    
    public void  mostrar (String resultado){
        txtAreaMostrarResultado.setLineWrap(true);
        txtAreaMostrarResultado.setWrapStyleWord(true);
        txtAreaMostrarResultado.setText(resultado); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSerieFibonacci;
    private javax.swing.JButton btnSeriePrimos;
    private javax.swing.JButton btnSeriesPares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaMostrarResultado;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
